set nocompatible                    " be iMproved, required
set encoding=utf-8                  " set character encoding inside vim

filetype off                        " required

if filereadable(expand("~/.dotfiles/vim/vimrc.vundles"))
  source ~/.dotfiles/vim/vimrc.vundles
endif

syntax on                           " required for syntax highlighting
filetype plugin indent on           " required
runtime macros/matchit.vim          " activate matchit

set completeopt=longest,menuone,preview

" Map the leader to spacebar rather than \
let mapleader = "\<Space>"

" Enable mouse support
set mouse=a
" Yank to system clipboard
set clipboard=unnamed

set hidden

" Plugin Syntastic
let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
nnoremap <leader>e :SyntasticCheck<CR>
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" Plugin airline + tmuxline
let g:airline_powerline_fonts=0
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_section_c = '%t'
let g:tmuxline_powerline_separators=0
let g:tmuxline_preset = {
    \ 'a': '#S',
    \ 'win': ['#I', '#W'],
    \ 'cwin': ['#I', '#W'],
    \ 'y': ['#(battery -tpa)  %b %d %R'],
    \ 'z': '#h',
    \'options' : {'status-justify' : 'left'}}

" Plugin ctrlp
let g:ctrlp_extensions = ['tag', 'buffertag', 'dir', 'line']
let g:ctrlp_custom_ignore={
  \ 'dir': '\v[\/](node_modules|tmp)|(\.(git|hg|svn|sass-cache))$',
  \ 'file': '\v\.(exe|so|dll|zip|swp|so|DS_Store)$'
  \ }
let g:ctrlp_use_caching = 0
let g:ctrlp_switch_buffer='ETVH'

" Plugin Dispatch
" Run rspec test
nnoremap <leader>s :Dispatch bin/rspec <c-r>=expand("%:p")<cr>:<c-r>=line(".")<cr> --format doc --color<cr>
nnoremap <leader>S :Dispatch bin/rspec <c-r>=expand("%:p")<cr> --format doc --color<cr>

" open up vimrc
nmap <leader>vr :tabedit $MYVIMRC<cr>
nmap <leader>vb :tabedit $HOME/.dotfiles/vim/vimrc.vundles<cr>
" reload vimrc
nmap <leader>so :source $MYVIMRC<cr>
" Pre-populate a split command with the current directory
nmap <leader>n :tabnew <C-r>=escape(expand("%:p:h"), ' ') . '/'<cr>
" Map 0 to ^
nmap 0 ^
" Move up and down by visible lines if current line is wrapped
nmap j gj
" nmap k g
" Exit Insert mode
imap jk <esc>
imap jj <esc>

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

set noswapfile                        " Don't create swap file
set nobackup                          " Don't create backup files

" Bind `q` to close the buffer for help files
autocmd Filetype help nnoremap <buffer> q :q<cr>
" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =
" Support hamlc syntax, because it's basically haml
autocmd BufRead,BufNewFile *.hamlc set ft=haml
" Support yaml front matter in markdown files
autocmd BufNewFile,BufRead,BufWrite *.md,*.html syntax match Comment /\%^---\_.\{-}---$/ contains=@Spell

autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd BufNewFile,BufRead *.scss,*.styl             set ft=css

let g:solarized_termcolors=256
set bg=dark                         " set background theme to be dark
colorscheme solarized
set lazyredraw                      " disable redraw during actions
set autoread                        " display file changes immediately
set ttyfast                         " more characters sent to the screen to for smoother redraws
set title                           " set the title to the value of 'titlestring'
set showmode                        " shows the current mode
"set showtabline=2                   " always show tabline
set showcmd                         " show the current command
set laststatus=2                    " always show status line
set number                          " enable line number
"set relativenumber
set cursorline                      " highlight cursor line
set backspace=indent,eol,start      " allow backspacing over everything
set history=500
set scrolloff=10                    " keep at least 10 lines below the cursor
set list                            " show spaces and tabs
set listchars=tab:»·,trail:·,nbsp:· " string represented in `list`
set colorcolumn=50,72               " indicate column lines for text wrap
set wrap                            " wrap line when lines are longer than the window width
set splitright                      " open new vertical split panes to right
set splitbelow                      " open new split panes to the bottom
set guifont=Monaco:h18              " set the font type and size
set visualbell                      " Set visual bell instad of a 'BEEP'
set noerrorbells                    " Turn off the bell
set wildmenu

" Use softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set softtabstop=2
set shiftround
set expandtab
set autoindent
set copyindent

" Highlight matching search term
set nohlsearch
set incsearch
set hlsearch
set ignorecase
set smartcase
" spacebar to turn off term highlighting
nnoremap <leader>h :nohlsearch<cr>
nnoremap ; :

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag
  let g:grep_cmd_opts='--line-numbers --noheading'
  let g:ag_prg="ag --vimgrep --case-sensitive"
  let g:ag_highlight=1

  " Use ag in ctrlp
  let g:ctrlp_user_command = 'ag %s -l --hidden --silent --nocolor -g ""'

  " bind \ to :Ag!
  nnoremap \ :Ag! --hidden --silent<space>
endif

" Toggle line numbers from static to relative
function! LineNumberToggle()
  if (&relativenumber == 1)
    set norelativenumber
  else
    set relativenumber
  endif
endfunc
nnoremap <c-S-n> :call LineNumberToggle()<cr>

function! BgToggle()
  if (&bg == "dark")
    set bg=light
  else
    set bg=dark
  endif
endfunc
nnoremap <F5> :call BgToggle()<cr>
set diffopt+=vertical

"nnoremap <leader>b Orequire 'pry-remote'; binding.remote_pry<esc>

let g:netrw_localrmdir='rm -r'
let g:netrw_localrmdir="rm -rf"
