export DOTFILES_ROOT="$HOME/.dotfiles"
export LANG=en_US.UTF-8
export EDITOR='vim'

source $DOTFILES_ROOT/zsh/scripts/antigen/antigen.zsh
source $DOTFILES_ROOT/zsh/scripts/antigen_bundles.zsh
source $DOTFILES_ROOT/zsh/scripts/functions.zsh
source $DOTFILES_ROOT/zsh/scripts/aliases.zsh

# Base16 Shell
# Sourcing this in tmux is not needed
if [ ! "$TERM" = "screen-256color" ] && [ ! -n "$TMUX" ]; then
  BASE16_SHELL="$DOTFILES_ROOT/zsh/scripts/base16-shell/base16-ocean.dark.sh"
  [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
fi

#if [[ "$(uname -n)" == "pewiz.local" ]]; then
export PATH="$HOME/.pollev/bin:$PATH"
#fi

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# nvm
export NVM_DIR="$HOME/.nvm"
  . "$(brew --prefix nvm)/nvm.sh"
