# Set default editor to vim
export EDITOR=vim

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='rg --ignore-file .gitignore --glob !.git --files-with-matches --follow --smart-case --threads 4 --hidden --regexp ""'

# rbenv init
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  source $(brew --prefix)/etc/bash_completion
fi

# Bash git prompt
if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="$(brew --prefix bash-git-prompt)/share"
  GIT_PROMPT_THEME=Custom
  source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi

if [ -f "$HOME/.config/tat/tat.sh" ]; then
  source $HOME/.config/tat/tat.sh
  export CODE_ROOT_DIRS="$HOME/Documents"
  export CODE_ROOT_DIRS="$HOME/Documents/projects:$CODE_ROOT_DIRS"
fi

if [ -f "$HOME/.config/tmux/bin/tmux" ]; then
  export PATH="$HOME/.config/tmux/bin:$PATH"
fi

# Alias
# git
alias gsha="git rev-parse HEAD | tr -d '\n' | pbcopy && git rev-parse HEAD"
alias glog="git log --graph --pretty=format:'%h - %d %s (%cr) <%an>' | vim -R -c 'set filetype=git nowrap' -"

# Foreman
alias f='bundle exec foreman start'

alias wake='caffeinate -dimsut 7200'

# NVM (node and npm version management)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Yarn (a faster npm alternaive)
export PATH="$HOME/.yarn/bin:$PATH"
